### ISSUE TITLE
SuperAdmin Navbar

### ISSUE THREAD

**Issue by SigmaCodex** [SigmaCodex/FindNCapstone#10]
SuperAdmin Edit the navbar color to white ang text to orange

**Comment by zendaz** [comment]
updated the text color from white to orange

**Comment by SigmaCodex** [comment]
Ivan ang navbar kay pangayoon nimo ni dublin

**Comment by zendaz** [comment]
ha? HAHAHAHA @barbecue2304  pangayoon nako imo navbar?
