### ISSUE TITLE
CheckBox

### ISSUE THREAD

**Issue by SigmaCodex** [SigmaCodex/FindNCapstone#41]
![image](https://user-images.githubusercontent.com/54108705/159430862-fd70744b-1f55-4619-adb1-be1b6209f576.png)

-remove the checkbox from AdminListTable
-Highlight The Name
-Change The "STATUS" table column -> EMAIL or Contact Number

**Comment by zendaz** [comment]
I have submitted PR for the issue. 

Thank you
